Fix formatting

diff --git a/.github/workflows/002-conditional-steps.yaml b/.github/workflows/002-conditional-steps.yaml
--- a/.github/workflows/002-conditional-steps.yaml
+++ b/.github/workflows/002-conditional-steps.yaml
@@ -1,35 +1,37 @@
 name: 02 Conditional Steps
 
 on:
-  workflow_dispatch:
+  workflow_dispatch:  # This event triggers the workflow manually
 
 jobs:
-  condtional-steps:
+  example_job:
     runs-on: ubuntu-latest
 
     steps:
       - name: Step 1 - Exit Code 0
-        id: successfull_step
+        id: successful_step
         run: |
           echo "exit code 0"
-          exit 0
-        shell: bash
-      
-      - name: Step 2 - Execute If Previous Step Succeeded
-        if: ${{ success() }}
+          exit 0  # Success (exit code 0)
+        shell: bash  # If you want you can change the shell per step
+
+      - name: Step 2 - Execute If Previous Succeeded
+        # The syntax bellow ${{}} is expression syntax in github actions (we will cover this later).
+        # Success and failure are status expressions.
+        if: ${{ success() }}  # Only run this step if the previous step succeeded
         run: |
-          echo "Running because the previous step succeeded"
-      
-      - name: Step 3 - I am failing
-        run:
+          echo "Running because the previous step has succeeded"
+
+      - name: Step 3 - I am Failing
+        run: |
           echo "I am failing"
-          exit 1
-      
-      - name: Step 4 - I will never execute
-        run:
+          exit 1  # Failure (non-zero exit code)
+
+      - name: Step 4 - I Will Never Execute
+        run: |
           echo "I will never execute"
 
-      - name: Step 5 - Execute on workflow failure
-        if: ${{failure()}}
+      - name: Step 5 - Execute on Workflow Failure
+        if: ${{ failure() }}  # Only run this step if the workflow failed
         run: |
-          echo "Workflow Failed"
+          echo "Workflow failed"
